### ISSUE TITLE
Menu Bar is disappeared in Settings.

### ISSUE THREAD

**Issue by Luigi1992** [Luigi1992/save-me#20]
When going to settings the menu simply disappear. It seems that is a bug of Android compatibility Library. 
Maybe the solution can be found here: http://stackoverflow.com/questions/17849193/how-to-add-action-bar-from-support-library-into-preferenceactivity

**Comment by Luigi1992** [comment]
It appears to be a bug of Google Support Library. Let's see if in a newer release they'll fix this error.

**Comment by alessio-balda** [comment]
Menu bar is now appearing on settings screen. However to do that, SettingsActivity is using a deprecated method which was previously used in SettingsFragment. It seems there are no changes, but we should remember this just in case.
