### ISSUE TITLE
Three images for three exam difficulty.

### ISSUE THREAD

**Issue by Luigi1992** [Luigi1992/save-me#33]
We have to create/find three images for describing the exam difficulty. This image will be placed in the exam card.

**Comment by alessio-balda** [comment]
Are these okay?

![test_icon_easy](https://cloud.githubusercontent.com/assets/6899721/6148345/02d37f5c-b201-11e4-827c-5d95a47a89bc.png)
![test_icon_hard](https://cloud.githubusercontent.com/assets/6899721/6148346/02d799c0-b201-11e4-95ff-8d43084f9ba6.png)
![test_icon_medium](https://cloud.githubusercontent.com/assets/6899721/6148347/02e79f32-b201-11e4-8cd0-e188d9a261a0.png)

**Comment by Luigi1992** [comment]
Yes, I think they are nice. Can you please integrate them in the project? Thank you! :)

**Comment by alessio-balda** [comment]
I've pushed them in the project!
